export const types = {
  USERS_LIST: '[chat] USERS_LIST',
  CHAT_ACTIVO: '[chat] CHAT_ACTIVO',
  CHAT_NEW_MESSAGE: '[chat] CHAT_NEW_MESSAGE',
  CHAT_MESSAGES: '[chat] CHAT_MESSAGES',
  SESSION_CLOSE: '[chat] SESSION_CLOSE',
}